Feat/graph abstraction
giospada/Automata-Visualizer pull request #12
Opened 2022-12-06 13:01 UTC by giospada

2022-12-06 15:59 UTC, Flecart requested changes
non compila

2022-12-06 19:13 UTC, Flecart commented on src/automata/dfa.rs
> +            .collect::<BTreeSet<usize>>();
ah, non sapevo si potesse fare anche così lel, fortissimo

2022-12-06 19:25 UTC, Flecart commented on src/automata/dfa.rs
> +            let mut set: BTreeMap<IndNode, IndEdge> = BTreeMap::new();
qui lo chiami set, ma in realtà è una map, avrebbe bisogno di un nome migliore, meglio se riguarda come lo utilizzi, che non ho capito benissimo, sembra che lo utilizzi per trovare l'indice dell'edge corrispondente

2022-12-06 19:29 UTC, Flecart commented on src/automata/nfa.rs
> +                format!("{}", node)
questa prima parte è esattamente identica al DFA, sarebbe meglio trovare un modo per metterlo in un unico posto.
Avrebbe senso creare una serie di funzioni in utils per questa roba ripetitiva?

Riguardo a BTreeSet possiamo implementare un trait into vec, se succede così tante volte.

2022-12-06 19:33 UTC, Flecart commented on src/automata/nfa.rs
> +        let mut g = Graph::new();
stessa cosa di g, dopo un pò non si capisce piùcosa sia

2022-12-06 20:15 UTC, Flecart reviewed
Questi sono i miei commenti riguardo alla tua PR, bella generalizzazione, un pò di nomi secondo me andrebbero rivisitati, però alla fine decidi te cosa meglio fare :man_shrugging:

2022-12-06 20:15 UTC, Flecart commented on src/utils/graph.rs
> +    fn bfs_connected_graph(
Ok, se ho capito bene questa è la funzione che effettivamente fa la bfs, la funzione precedente bfs, fa tutti i checks necessari e lo fa anche per grafi che non siano componenti connesse, kk buono, non ho proprio idea su come trovare un nome migliore per questo....

Però aspetta, se mi immagino un albero, ma parto a fare la bfs da un figlio di albero, e solo alla seconda iterazione parte dal root, che grafo ho poi? questa `bfs_connected_graph` non va a visitare il padre, quindi non è presente tra quello che ritorna, non ho capito cosa hai di output se succede quello, e se è l'ouput che vorresti.

2022-12-07 16:47 UTC, giospada commented on src/automata/nfa.rs
> +                format!("{}", node)
ma tanto vale perchè è solo per aggiungere i nodi al grafo per gli edge è diverso

2022-12-07 17:07 UTC, giospada commented on src/utils/graph.rs
> +    fn bfs_connected_graph(
alla funzione bfs viene passato il punto di partenza glie lo dai tu la prima volta volendo, se non gli dai niente lo prende a caso. a quel punto esplora tutti i nodi che riesce a vedere. se non sono stati esplorati tutti i nodi, prende un nodo a caso e parte ad esplorare da quello e aggiunge questo ordine d'esplorazione all'output finale


`bfs_connected_graph` esplora tutti i nodi raggiungibili  dal nodo che gli viene passato, non ancora esplorati

2022-12-07 17:10 UTC, giospada commented on src/display/display_graph.rs
> +    fn draw_edge_and_get_label_pos(
no collision indica che tra il nodo `t` e il nodo `s` esiste un arco che va da t a s e uno che va da s a t

`t -> s`
`s -> t`

prova con l'espressione `(a|b)*(a|b)` nel dfa ci dovrebbero essere archi di quel tipo

2022-12-07 20:31 UTC, Flecart requested changes
@giospada non compila, ma perché continui a fare il merge, setta correttamente quel git pull se te le fa in automatico. Prolly secondo me fai male a risolvere i conflitti e non provi a compilare quando li risolvi

2022-12-08 08:12 UTC, merged